### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gino2014** [scgoeswild/Magento2-admin-theme#1]
First of all thanks for providing this extension. 
We installed it but could not find a menu at the backend where we can change the logo.
Could you please advise us how we can change the logo.
Thanks in advance
Gino

**Comment by scgoeswild** [comment]
Hi there, 
you can copy and paste the folder in app/code and change the logo images under "view/adminhtml/web/images"

**Comment by gino2014** [comment]
Hello [scgoeswild](https://github.com/scgoeswild), 
thanks for the fast answer. Have a nice day.
Kind regards
Gino
